# Generated by Django 5.0.7 on 2024-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='furigana',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_back',
            field=models.ImageField(blank=True, upload_to='id/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_front',
            field=models.ImageField(blank=True, upload_to='id/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='insurance_card_back',
            field=models.ImageField(blank=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='insurance_card_front',
            field=models.ImageField(blank=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
