# Generated by Django 5.0.7 on 2024-08-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_address_1_profile_address_2_profile_furigana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='furigana',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_back',
            field=models.ImageField(blank=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card_front',
            field=models.ImageField(blank=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurance_card_back',
            field=models.ImageField(blank=True, upload_to='insurance_cards/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insurance_card_front',
            field=models.ImageField(blank=True, upload_to='insurance_cards/'),
        ),
    ]
