# Generated by Django 5.0.7 on 2024-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
