# Generated by Django 5.0.7 on 2024-08-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_appointment_meet_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='created_at',
        ),
    ]
