# Generated by Django 5.0.7 on 2024-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_medicalhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('completed', '完了'), ('in_progress', '予約中'), ('cancelled', '取消'), ('expired', '期限切れ')], default='in_progress', max_length=20),
        ),
    ]
