# Generated by Django 5.0.7 on 2024-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
