# Generated by Django 5.0.7 on 2024-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_appointment_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom_or_medicine_categoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
