# Generated by Django 5.0.7 on 2024-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
