# Generated by Django 5.0.7 on 2024-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_medicine_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
